### ISSUE TITLE
Version 10 of react-styleguidist minimum requirement is 8.12, not 8.9

### ISSUE THREAD

**Issue by lhornsby** [styleguidist/react-styleguidist#1516] opened 2020-01-08 20:06 UTC
**Current behavior**

The documentation for the release of v10.0.0 states that:

`Node 8.9 is the lowest supported version`

While attempting to update our project to v10 of React, my co-worker couldn't build the project but I could. His local machine is running Node 8.11.1. Mine is 8.12. 

After combing through RSG release notes, he found that the package `mini-html-webpack-plugin` was updated in v10 and [checked the release notes on that version](https://github.com/styleguidist/mini-html-webpack-plugin/releases/tag/v1.0.0), which state: 

`Node 8.12 is the minimum required version.`

This is especially an issue for our group because other internal processes required to build projects are below the 8.12 version of Node as well. 

**To reproduce**
Attempt to run Styleguidist in an environment with a Node version that less than 8.12. (I'm not certain how to provide an example for this, as it depends on a developer's local environment)

**Expected behavior**
Updates to Styleguidist documentation that provide clarity about the current minimum required version of Node. I had already done some custom styling and other additional work that now unfortunately must be cherrypicked out of my branch to implement, so some form of documentation with this clarity would be useful to other developers.

**Comment by sapegin** [comment] 2020-02-18 07:50
Feel free to send a pull request to update the version in `package.json`.

**Comment by mitsuruog** [comment] 2020-02-21 11:04
one idea is to change the next LTS version (10.13.0).
but I afraid it might affect current users, so we have to decide whether to make it the current version or include it in the next major update.

what do you think?

**Comment by sapegin** [comment] 2020-02-21 11:10
I think it's easier, for now, to add the correct version number to `package.json`. This would be patch release because it was already not working in older versions.

Changing it to 10.x would be major release, even with no other changes. Though we can do it too in 11.x

**Comment by mitsuruog** [comment] 2020-02-21 14:19
Let me check which version is currently working later.

**Comment by mitsuruog** [comment] 2020-02-22 04:15
I had tested by some node versions, but I could not reproduce it. 
I guess "Node 8.9 is the lowest supported version" is correct so far.

Here is how have been tested.

- Environment
  - OS: mac
  - Node version management tool: nvm
- Preparing
  - Use `/examples/basic` example in this project.
  - Update `react-styleguidist` to 10.6.2
- Test steps
  - Change node version by `nvm use XXX`
  - Check current node version by `node -v`
  - `npm install`
  - `npm run styleguide`
  - Check if the styleguide is not break
  - `npm run styleguide:build`
  - `npx http-server styleguide` 
  - Check if the styleguide is not break
- Tested node versions
  - 8.9.0
  - 8.10.0
  - 8.11.0
  - 8.11.1
  - 8.12.0

@lhornsby 
could you make a reproducible minimum example there to make clear the cause?

https://codesandbox.io/

**Comment by lhornsby** [comment] 2020-02-22 21:02
@mitsuruog I would need to check with my co-worker to try to reproduce an example as I don't remember all the differences between our machines. Specifically, we're both using mac OS. Mine has a later version of both Node and Yarn. 

I think he may have disabled/lowered the version of the `mini-html-webpack-plugin` package locally (the one with the release notes regarding Node 8.12) and was able to build Styleguidist when that package wasn't installed, but I'll double-check.

**Comment by mitsuruog** [comment] 2020-02-27 12:43
@lhornsby how's it going?

btw I possibly met this issue.
actually I tried to make a new commit in this project, then I could not make it by this error appears.
so I needed to upgrade my node version to 8.12.0.
 
```
husky > pre-commit (node v8.9.0)
lint-staged requires at least version 8.12.0 of Node, please upgrade
husky > pre-commit hook failed (add --no-verify to bypass)
```

so In this case, the minimum required version must be `8.12.0`. 
but it is for the development purpose though.

@sapegin what do you think?

**Comment by sapegin** [comment] 2020-02-27 13:01
I think we can update the version in `11 ` branch and make Node 10 the minimum since 8.x isn't supported anymore and 11 is a major release anyway.

**Comment by mitsuruog** [comment] 2020-02-27 13:25
Sure. I leave it as is a while.
I am happy if somebady close it once the v11 gets released. Thanks!

**Comment by mitsuruog** [comment] 2020-03-17 12:33
@sapegin would you close it?

**Closed** 2020-03-17 13:01 UTC
Labels: good first issue, help wanted
