### ISSUE TITLE
Upgrade to react-docgen 5.0

### ISSUE THREAD

**Issue by thecodejack** [styleguidist/react-styleguidist#1498] opened 2019-12-14 08:22 UTC
Now that react-docgen@5.0.0 is available, when are we planning to upgrade same with styleguidist. https://github.com/styleguidist/react-styleguidist/issues/1354 seems to have been blocked.

**Comment by sapegin** [comment] 2019-12-15 07:38
As soon as anyone submits a pull request with an upgrade, it's an open source project.

Duplicate of #1354.

**Closed by sapegin** 2019-12-15 07:38 UTC
