### ISSUE TITLE
I can't use arrow function in markdown 

### ISSUE THREAD

**Issue by hongyin163** [styleguidist/react-styleguidist#1433] opened 2019-09-14 09:49 UTC
When I write demo in reademe.md file，I can't write  arrow function in class
```
import React,{Component} from 'react';

class Demo extends Component{
    constructor(props,context){
        super(props,context);
        const me=this;
        me.state = {checked:false};
    }
    // I can't do this
    onChange=(checked)=>{
        this.setState({
            checked
        })
    }
    render(){
        const me=this;
        const {
            checked
        }=me.state;
        return (
            <Radio.Group>
                <Radio checked={checked} onChange={me.onChange} />
            </Radio.Group>
        )
    }
}

<Demo/>
```

`

but i can do this in js file

**Comment by sanwjt** [comment] 2019-09-17 07:32
I have the same problem，do you solved it.    i do not want to bind this in constructor

**Comment by hongyin163** [comment] 2019-09-22 04:44
> I have the same problem，do you solved it. i do not want to bind this in constructor

I write demo in demo folder, and import it in readme file

you need add this option
```
    updateExample(props, exampleFilePath) {
        // props.settings are passed by any fenced code block, in this case
        const { settings, lang } = props;
        // "../mySourceCode.js"
        if (typeof settings.file === 'string') {
            // "absolute path to mySourceCode.js"
            const filepath = path.resolve(exampleFilePath, settings.file);
            // displays the block as static code
            // settings.static = true
            // no longer needed
            delete settings.file;
            return {
                content: fs.readFileSync(filepath, 'utf8'),
                settings,
                lang
            };
        }
        return props;
    },
```
In readme file

```
Demo源码：
```js { "static":true,"file": "../demo/index.tsx" }
```
```

**Comment by sapegin** [comment] 2019-10-30 10:38
Duplicate of #1438.

**Closed by sapegin** 2019-10-30 10:38 UTC
