### ISSUE TITLE
react-docgen version is low

### ISSUE THREAD

**Issue by hfuuss** [styleguidist/react-styleguidist#1283] opened 2019-02-21 08:54 UTC
![Uploading image.png…]()

react-docgen latsed version is 4.0.0 now ，when i use react-styleguidist version 9.0.0 ，it warning： 

RangeError: Maximum call stack size exceeded

**Comment by sapegin** [comment] 2019-02-22 15:14
Duplicate of #1279.

**Closed by sapegin** 2019-02-22 15:14 UTC
