### ISSUE TITLE
Error: import or require() statements can be added only by editing a Markdown

### ISSUE THREAD

**Issue by davidpaley** [styleguidist/react-styleguidist#1312] opened 2019-03-07 17:36 UTC
I'm trying to make an example of my component in the Markdown file (.md). The problem is when I try to import something inside this markdown file:

```jsx inside Markdown
import { validateEmail } from '../../utils/validation';

initialState = {
  value: 'asdas',
}

function updateValue(name, value) {
  setState({ [name]: value });  
}

<Input
  placeholder="Name"
  value={value}
  type="text"
  required={true}
  name="value"
  onChangeFunction={updateValue}
  validations={[validateEmail]}
/>;
```

When I go to the component it says:
Error: import or require() statements can be added only by editing a Markdown example file: ../../utils/validation

![image](https://user-images.githubusercontent.com/4527780/53976091-14abc280-40e5-11e9-91c7-3ff4351d9259.png)

I tried also with require but it didn't work.

versions:
- react-styleguidist": "^9.0.3"
- "react": "^16.7.0",

Example of my project: 
https://github.com/aimementoring/blueprint
branch: feature/validations

**To reproduce**
- download the project and execute:
- yarn
- yarn deploy
- serve -s styleguide
- go to the input component.

**Comment by kopax** [comment] 2019-03-07 17:41
I think this is the same as #1310, we are currently invistagating for the root cause but we couldn't find, let us know if you get why. To me, all the module aliases are not working within examples.

The one think we can import is `react`. Can you please confirm that you can't import dependencies listed in `package.json` `dependencies` ?

**Comment by davidpaley** [comment] 2019-03-07 18:05
Yes, me too. I have the error if I tried to import any of the package.json dependencies except for react.

**Comment by timsnadden** [comment] 2019-03-07 18:34
Try deleting `yarn.lock/package-lock.json` and reinstalling. I'm not sure which dependency is causing the issue but this fixes it

**Comment by kopax** [comment] 2019-03-07 18:58
@timsnadden I don´t know where you got this. I am a package maintainer and we allow the wider range of semver for our users, We want to see things break and we do not use lock file for that reason (except in app). The only thing it could have change on your side is that it  upgraded version on your particular host. To me, I already have the latest version and this bug is still present. You´re advice won´t help.

**Comment by timsnadden** [comment] 2019-03-09 00:54
@kopax For me the issue was resolved by removing `yarn.lock` and reinstalling. It's a hacky solution but can perhaps provide a clue to identify the root cause. I'm sorry it didn't resolve the issue for you

**Comment by kopax** [comment] 2019-03-09 06:38
Ok, now I got it and you are right. Let's continue in #1278

**Comment by sapegin** [comment] 2019-03-26 07:53
This should be

**Closed by sapegin** 2019-03-26 07:53 UTC
Labels: duplicate
