### ISSUE TITLE
Code blocks with syntax doesn't get evaluated

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#267] opened 2016-12-22 16:35 UTC
It seems it only evaluates examples if there is no syntax specified for the code block. I.e. this

![2016-12-22 at 17 34](https://cloud.githubusercontent.com/assets/11071/21432682/d8a22768-c86c-11e6-860b-8692b659eded.png)

results in following:

![2016-12-22 at 17 33](https://cloud.githubusercontent.com/assets/11071/21432632/b5e12b66-c86c-11e6-9dfe-43dfbf3c83ac.png)

And since I'd like to still have code highlight on GitHub.

I'd say it should be able to parse the language part of the code block and evaluate it if it's `jsx?` match.

And if the syntax isn't specified, it will try to evaluate the contents as JavaScript:

![2016-12-22 at 17 30](https://cloud.githubusercontent.com/assets/11071/21432605/97515a04-c86c-11e6-92d0-362acb1ad5d3.png)

I'd say the second isn't an issue, although it would be nice if it could check if it's a valid syntax (`try catch`?)

**Comment by okonet** [comment] 2016-12-22 16:45
And looking at https://github.com/styleguidist/react-styleguidist/blob/master/examples/sections/lib/components/Button/Readme.md I see it's by design. 

But this is a bad DX IMO and can be improved.

**Comment by sapegin** [comment] 2016-12-22 16:56
Yes, that‘s exactly how it should work.

> But this is a bad DX IMO and can be improved.

If you have any ideas feel free to submit a pull request or open an issue. Comments like that are unproductive.

Related issues: #257, #265.

**Comment by okonet** [comment] 2016-12-22 17:15
I actually wrote down my ideas:

* It should be able to parse the language part of the code block and evaluate it if it's jsx? match.
* It would be nice to check if it's a valid syntax (using `try ... catch` block perhaps?)

**Comment by sapegin** [comment] 2016-12-22 17:17
What should we do if you have a typo in JS? It doesn‘t have to contain JSX, any JS should work.

**Comment by sapegin** [comment] 2016-12-22 17:17
In any case we need a way to explicitly define how to render an example.

**Comment by sapegin** [comment] 2016-12-22 17:20
For example: how to render a piece of JS code as highlighted code, not as a playground?

**Comment by okonet** [comment] 2016-12-23 09:33
Yeah, that's an interesting problem. I'm not sure how to answer all these questions. Thanks for bringing it up! I'll think about it tho.

**Comment by sapegin** [comment] 2016-12-23 09:35
I agree that the current solution isn’t perfect but the problem isn’t as easy either. Could you create a new issue, and I‘ll close this one, since it’s a bug report ;-)

**Closed** 2017-01-02 19:34 UTC
Labels: wontfix
