### ISSUE TITLE
webpack render error with latest rc version

### ISSUE THREAD

**Issue by sjy** [styleguidist/react-styleguidist#356] opened 2017-03-16 12:19 UTC
![image](https://cloud.githubusercontent.com/assets/1523060/23995512/df99ddf4-0a84-11e7-9f83-7082ab47f07f.png)

I get the error message when the command
```
node_modules/.bin/styleguidist server
```

I have installed the latest rc version 
```javascript
{
...
    "react-styleguidist": "^5.0.0-rc.1" ,
    "webpack": "^2.2.1",
    "webpack-dev-server": "1.14.1"
...
}
```
I failed to open the guide page served by the webpack-dev-server;
Any clues ?

**Comment by sapegin** [comment] 2017-03-16 12:43
Looks like it can’t find a name of your component.

1. Did it work before? This place was changes several 5.x betas before.
2. Could you show your style guide config?
3. Try to limit `components` option to one component and see it happens to all your components or just one of them. In any case component’s source would be helpful.

**Comment by sjy** [comment] 2017-03-16 15:41
1.yes, my code works before I re-installed the dependencies;

2.here is my configure file;
```javascript
/*eslint-env node*/
const path = require('path');

module.exports = {
    title:'Guide',
    components: 'src/components/**/*.js',
    styleguideDir: './docs',
    skipComponentsWithoutExample: true,
    showCode: false,
    serverPort: 7000,
    verbose: true,
    context: {
        generateData: path.resolve(__dirname, 'src/utils/generateData')
    },
    getComponentPathLine: function(componentPath) {
        const name = path.basename(componentPath, '.js');
        const dir = path.dirname(componentPath);
        return `import ${name} from '${dir.replace('src/', 'lib/')}';`;
    },
    getExampleFilename(componentpath) {
        return componentpath.replace(/\.js?$/, '.md');
    },
    webpackConfig(env) {
        const dirs = [
            path.resolve(__dirname, 'src'),
            path.resolve(__dirname, 'node_modules/react-dates'),
            path.resolve(__dirname, 'node_modules/hui'),
            path.resolve(__dirname, 'node_modules/react-styleguidist'),
            path.resolve(__dirname, 'styleguide'),
        ];

        return {
            resolve: {
                enforceExtension: false,
                alias: {
                    components: path.resolve(__dirname, 'src/components'),
                    'rsg-components/StyleGuide/StyleGuideRenderer': path.join(__dirname, 'styleguide/StyleGuide'),
                    'rsg-components/ReactComponent/ReactComponentRenderer': path.join(__dirname, 'styleguide/ReactComponent'),
                },
            },
            module: {
                rules: [
                    {
                        test: /\.(js|jsx)$/,
                        include: dirs,
                        use: ['babel-loader'],
                    },
                    {
                        test: /\.(scss|css)$/,
                        include: dirs,
                        use: [
                            'style-loader',
                            'css-loader',
                            'sass-loader',
                        ],
                    },
                    {
                        test: /\.svg$/,
                        include: path.resolve(__dirname, 'styleguide'),
                        use: 'babel!react-svg',
                    },
                    {
                        test: /\.(eot|svg|ttf|woff|woff2)$/,
                        include: path.resolve(__dirname, 'node_modules/hui'),
                        use: 'url-loader?limit=10000',
                    }
                ],
            }
        };
    }
};
```

3 I found out the cause is I customied the style by add alias rules to webpack.

Thanks for your help

**Comment by sapegin** [comment] 2017-03-16 15:50
It is a recommended way but there’s no easy way to make it stable. If we change something in Styleguidist components, you may need to update your customizations.

**Comment by sjy** [comment] 2017-03-16 15:53
Thank again 😄  you are pretty helpful 👍 I would follow the official examples and report an issue if I find anything doesn't make sense.

**Comment by sapegin** [comment] 2017-03-16 15:55
Awesome! Could we close this issue or you still have some questions? ;-)

**Comment by sjy** [comment] 2017-03-16 15:59
Let it open right now, I am still facing the issue even remove the customized stuff.

**Comment by sjy** [comment] 2017-03-16 16:56
Please close this issue. It is due to one of my example.md with empty content wrapped in "``"

``` markdown
    ```
      <empty content>
    ```
```

**Comment by sapegin** [comment] 2017-03-16 17:40
This looks like a bug but I can’t reproduce it.

**Comment by sapegin** [comment] 2017-03-27 07:50
Closing this for now. Feel free to reopen with more details.

**Closed by sapegin** 2017-03-27 07:50 UTC
Labels: bug
